### ISSUE TITLE
SLPM meters...

### ISSUE THREAD

**Issue by whitsonk** [huilab/HoneywellZephyrI2C#1]
According to the data sheet for SLPM meters...
https://sensing.honeywell.com/honeywell-sensing-zephyr-digital-airflow-10-slpm-300-slpm-datasheet-008268-5-en.pdf

The SLPM meter flow() function should be...
    Full Scale Flow * [(Digital Output Code/16384) - 0.1]/0.8

Perhaps there should just be two flow() functions in HoneywellZephyrI2C.h? 
i.e....
    float flowSCCM() const { return _FLOW_RANGE * ( ( (float)_count/16384.0) - 0.5)/0.4; }
    float flowSLPM() const { return _FLOW_RANGE * ( ( (float)_count/16384.0) - 0.1)/0.8; }

**Comment by erikmwerner** [comment]
Great suggestion, I didn't realize the SLPM sensors have a different transfer function.

There is now an enumeration for SCCM or SLPM sensor types and the constructor lets you select either a SCCM or SLPM sensor. The proper transfer function is selected by the flow() function. It is untested as I don't have SLPM sensors, but it should be straightforward.
